### ISSUE TITLE
Generic interfaces

### ISSUE THREAD

**Issue by ivan-pi** [14NGiestas/mfi#5]
Hello @14NGiestas,

Digging through the [BLAS forum](http://www.netlib.org/blas/blast-forum/), I found a document describing a "Fortran 95 thin BLAS": http://www.netlib.org/blas/blast-forum/f95thinblas.pdf

The document proposes to build generic interfaces with respect to:
* data type
* precision
* rank
* argument list

I believe that the [LAPACK 95](http://www.netlib.org/lapack95/index.html) and [Intel MKL Fortran Interfaces for LAPACK 95](https://software.intel.com/content/www/us/en/develop/documentation/mkl-developer-reference-fortran/top/lapack-routines/fortran-95-interface-conventions-for-lapack-routines/intel-mkl-fortran-95-interfaces-for-lapack-routines-vs-netlib-implementation.html) are partial or even full implementations of this proposal. It seems kind of annoying that their interfaces diverged slightly. [NAG](https://www.nag.com/numeric/nl/nagdoc_latest/flhtml/f07/f07conts.html) on the other hand seems to only export the low level interfaces, however inspection of the LAPACK 95 interface files shows that NAG was also involved in their development.

I assume you would like this layer to work with any compiler/custom LAPACK library, so it makes to sense (re)build the modern/generic interfaces from the low-level ones. It does feel though, like re-inventing the wheel. 

I am interested in what do you think can be done differently using fypp? 

The LAPACK 95 seems to have integrated some error checking of arguments. This is one of the things which could be perhaps simplified with fypp.

**Comment by 14NGiestas** [comment]
Hi @ivan-pi 
My main goal here is to fix some divergences, missing interfaces and hopefully improve the availability of such procedures to newcomers (fpm?, cmake?). It happens that LAPACK95 is [incomplete](http://www.netlib.org/lapack95/lug95/node340.html), the `LA_POTRF`, for instance, has the same interface as a F77 except it overloads each supported type/rank, Intel's MKL on the other hand, do a better job as you can see it [here](https://software.intel.com/content/www/us/en/develop/documentation/mkl-developer-reference-fortran/top/lapack-routines/lapack-linear-equation-routines/lapack-linear-equation-computational-routines/matrix-factorization-lapack-computational-routines/getrf.html#getrf), all those little annoyances made me start working on this thing here.

I want to make my code readable while keeping its performance, but I don't want to change my code each time I have to support a new compiler/library provider (or handle it using macros thus polluting the main code). No matter what you are using in the background, the modern interface will remain the same and will be flexible enough to use for years to come. The fypp will help me (and possible contributors) to write way less code in order to finish this project.

PS: f95thinblas is a proposal to improve BLAS interfaces, it should not be confused with Netlibs LAPACK95, that implements only lapack F95 interfaces.

**Comment by ivan-pi** [comment]
> PS: f95thinblas is a proposal to improve BLAS interfaces, it should not be confused with Netlibs LAPACK95, that implements only lapack F95 interfaces.

You are right. I failed to recognize this. So the "thin" BLAS generic interface is a very good initial target to demonstrate the entire concept.

**Comment by awvwgk** [comment]
> I want to make my code readable while keeping its performance, but I don't want to change my code each time I have to support a new compiler/library provider (or handle it using macros thus polluting the main code).

I think I have used three different BLAS/LAPACK wrappers so far and also created my own for some projects, because they never really met my requirements. Creating a persistent solution for this purpose sounds ambitious to me, but I would be happy to test or use this project.

**Comment by 14NGiestas** [comment]
closing this since it seems solved, any further questions feel free to open a discussion.
